[package]
name = "capture_log"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0"
rusqlite = { version = "0", features = ["bundled"] }
# tesseract = "0.8.0"
image = "0.23.14"
leptess = "0"
regex = "1"
rdev = "0"

[build-dependencies]
bindgen = "0.70.1"
