[package]
name = "capture_log"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0", features = [
    "Win32_System_Wmi",
    "Win32_System_Diagnostics_Etw",
    "Win32_System_EventLog",
] }
sysinfo = "0"
rusqlite = { version = "0", features = ["bundled"] }
